### ISSUE TITLE
Ask a question: Limit CI workflow runs to languages

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/v3#123]
https://github.com/exercism/v3/actions?query=workflow%3A%22Julia+CI%22

Julia CI seems to run on each push. Is it possible to check if it was a push to a `.../julia/exercises/**/*`? I love the idea of adding JavaScript CI and TypeScript CI but don't want to waste everyone's time and GH resources.

---

Summary of the responses below.

You can restrict Actions workflows to only run when they affect files in a language directory by using the following trigger conditions:

```yaml
on:
  push:
    paths:
    - '**.$EXT'
    - 'languages/$SLUG/**'
  pull_request:
    paths:
    - '**.$EXT'
    - 'languages/$SLUG/**'
```

Further notes on using Actions:

If you use **any** action in your workflow that requires access to the GitHub token or other secrets, use the commit hash of the release instead of the version tag. Version tags are mutable and a malicious actor could point them at whatever code they want, thus gaining access to this repo. Note that you should use commit hashes for **all** actions in the workflow, because they could manipulate the environment to inject their code even if the action itself doesn't have access to any secrets.

For example:

```yaml
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@04aa5dbc72538e0b9194c658a9ad6026b865d039 # 2.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

instead of 

```yaml
    - uses: actions/labeler@v2.1.0
```
