### ISSUE TITLE
[Roadmap] Docker compose configuration

### ISSUE THREAD

**Issue by joshgoebel** [exercism/v3#2132]
**This is a rough outline of how the new "build stack" Docker Compose functionality might work. Your thoughts would be very appreciated :)**

---

To get a whole Exercism stack up and running (from binary Docker images):

```bash
git clone git@github.com:exercism/v3-docker-compose.git
cd v3-docker-compose
cp stack.default.yml stack.yml
./bin/build_stack
docker-compose up
```

`build_stack` is just a tiny utility to avoid having to maintain (and deal with merge conflicts) with a huge highly-customized/commented `docker-compose.yml` since most maintainers will need different parts of the full project.  If you only work on Javascript Track you likely don't care about 100 other test runners and analyzers... so you'd likely edit stack.yml and just enable the JS related bits (in addition to the core site).

To customize your stack simply edit stack.yml `enabled`:

```yaml
# stack.yml

enabled:
  # s3, dynamodb, redis, startup
  - core_services  
  # the main Rails web application 
  - website
  - tooling
  # disable to save RAM if you don't use portainer or adminer much
  - admin
  # add any specific components you'd like to work with here such
  # as specific tracks runners/analyzers, etc.
  - javascript-analyzer
  - javascript-test-runner
```

Then rebuild with `./bin/build_stack`.

```bash
./bin/build_stack
docker-compose stop
docker-compose up --build
```

To configure the Docker images or build them yourself use `configure`:

```yaml
#stack.yml

enabled:
  ...

configure:
  startup:
    environment:
      - FASTER_PLEASE=yes
  javascript-test-runner:
    build: true
```

Then rebuild:

```bash
./bin/build_stack
docker-compose build
```

Any keys specified (other than just `build: true`) will be merged into those found in the main (very huge) `docker-compose-full.yml`.  This allows you to customize individual services via normal Docker Compose keys to better suite your local requirements.  Any changes that are "permanent" or should be pushed to all users would be committed to the HUGE docker compose template file.

Building would also require checking out the repo/component you intended to build into the directory above `v3-docker-compose`, so you're overall directory structure would look like:

```
exercism
\-- v3-website
\-- v3-docker-compose
\-- javascript-test-runner
\-- tooling-invoker
```

Jeremy suggesting merging configure and enabled but I like being able to turn something on and off without deleting its configuration.  IE, it's just commenting a single line.  IE, first you decide what services to enable, then you configure them.

Configuring should be less common.

---

Full sample `stack.yml`:

```yaml
enabled:
  # s3, dynamodb, redis, startup
  - core_services
  - website
  - tooling
  # disable to save RAM if you don't use portainer or adminer much
  - admin
  # add any specific components you'd like to work with here such
  # as specific tracks runners/analyzers, etc.
  - javascript-test-runner

configure:
  tooling-invoker:
    environment:
      - POLLING_DELAY=5
  javascript-test-runner-base:
    build: true
  javascript-test-runner:
    build: true
    environment:
      - BOOGER=321

# allow configuration of groups to enable/disable all at once
# though we might move this back into the primary configuration file
groups:
  core_services:
    - startup
    - redis
    - dynamodb
    - s3
  admin:
    - adminer
    - portainer
  tooling:
    - tooling-invoker
    - tooling-orchestrator
  analyzers:
    - none
  test-runners:
    - csharp-test-runner
    - javascript-test-runner
```
